"""Dynamic multi-agent pipeline with JSON schema validation."""
from __future__ import annotations

import importlib
import json
from pathlib import Path
from typing import Dict, List

import jsonschema

AGENT_MODULES: List[str] = [
    "chatgpt_agent",
    "claude_agent",
    "gemini_agent",
    "cursor_agent",
]

INPUT_SCHEMA = {
    "type": "object",
    "properties": {"prompt": {"type": "string"}},
    "required": ["prompt"],
}

OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {"response": {"type": "string"}},
    "required": ["response"],
}


def sync_documents() -> None:
    """Synchronise design, code skeleton and tests from requirements."""
    req_path = Path("docs/requirements.md")
    if not req_path.exists():
        return
    content = req_path.read_text(encoding="utf-8")

    # Update design and test documents
    design_path = Path("docs/design.md")
    test_doc_path = Path("docs/tests.md")
    design_path.write_text(
        f"# Design\n\nGenerated from requirements.\n\n{content}\n",
        encoding="utf-8",
    )
    test_doc_path.write_text(
        f"# Test Plan\n\nGenerated from requirements.\n\n{content}\n",
        encoding="utf-8",
    )

    # Generate simple code and test placeholders
    code_path = Path("src/requirements_generated.py")
    test_path = Path("tests/test_requirements_generated.py")
    code_path.parent.mkdir(parents=True, exist_ok=True)
    test_path.parent.mkdir(parents=True, exist_ok=True)
    code_path.write_text(
        f'"""Autogenerated module from requirements."""\n{content}\n',
        encoding="utf-8",
    )
    test_path.write_text(
        f'"""Autogenerated tests from requirements."""\n{content}\n',
        encoding="utf-8",
    )


def run_pipeline(prompt: str) -> Dict[str, str]:
    jsonschema.validate({"prompt": prompt}, INPUT_SCHEMA)
    sync_documents()
    responses: Dict[str, str] = {}
    for module_name in AGENT_MODULES:
        module = importlib.import_module(f"src.agents.{module_name}")
        agent = module.Agent()
        try:
            result = agent.run(prompt)
            jsonschema.validate({"response": result}, OUTPUT_SCHEMA)
            responses[module_name] = result
        except Exception as exc:  # noqa: BLE001
            agent.feedback(str(exc))
            responses[module_name] = ""
    return responses


def auto_pr(body: str) -> None:
    """Placeholder for automatic PR creation and merge."""
    print("PR body:\n" + body)


if __name__ == "__main__":
    import sys

    input_prompt = sys.argv[1] if len(sys.argv) > 1 else "Hello"
    results = run_pipeline(input_prompt)
    if all(results.values()):
        auto_pr(json.dumps(results, indent=2))
    print(json.dumps(results, indent=2))
